server:
  port: 8200
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/microservices

  profiles:
    active: native

management:
  security:
    enabled: false
